[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "day01",
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trie-rs = "0.1.1"
